export const GET_MEALS_INIT = 'GET_MEALS_INIT'
export const GET_MEALS_SUCCEEDED = 'GET_MEALS_SUCCEEDED'
export const GET_MEALS_FAILED = 'GET_MEALS_FAILED'

export const CREATE_MEALS_INIT = 'CREATE_MEALS_INIT'
export const CREATE_MEALS_SUCCEEDED = 'CREATE_MEALS_SUCCEEDED'
export const CREATE_MEALS_FAILED = 'CREATE_MEALS_FAILED'

export const AUTH_FETCH_INIT = 'AUTH_FETCH_INIT'
export const AUTH_FETCH_SUCCEEDED = 'AUTH_FETCH_SUCCEEDED'
export const AUTH_FETCH_FAILED = 'AUTH_FETCH_FAILED'

export const GET_RESTAURANTS_INIT = 'GET_RESTAURANTS_INIT'
export const GET_RESTAURANTS_SUCCEEDED = 'GET_RESTAURANTS_SUCCEEDED'
export const GET_RESTAURANTS_FAILED = 'GET_RESTAURANTS_FAILED'